config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  get 'pages/about'

  get 'pages/contact'

  get 'pages/faqs'
end

app/models/story.rb
class Story < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def faqs
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Branddify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navbar' %>
	<div class="container-fluid">
		<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>
		<%= yield %>
		<%= render 'shared/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="fw about-page">
	<div class="about_banner">
    	<img src="/assets/about.jpg" alt="" class="img-responsive">
        <h2>ABOUT US</h2>
    	<div class="about_description">
        	<div class="container">
            	<div class="row">
                	<div class="col-md-4 col-sm-7 col-md-offset-1">
                    	<h3>REPRESENT YOUR STORY WITH A SIMPLE PHOTO </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempos incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quit nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div class="watwhy-sec fw">
    	<div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                	<img src="/assets/what.jpg" alt="">
                    <h4>WHAT ABOUT BRANDDIFY </h4>
                    <p>BRANDDIFY is a marketing foundation located in Riyadh built on the talent of creation that leads to a modern concept of professionalism. At Branddify we believe even if you are good at what you do, you have a great product or you provide an excellent service give your business the perfect image. </p>
                </div>
                <div class="col-md-6 col-sm-6">
                	<img src="/assets/whytree.jpg" alt="">
                    <h4>WHY WE EXIST </h4>
                    <p>Reaching customer satisfaction through providing them with cutting-edge technologies that give clients access to a wide range of tools, ensuring efficient and results-oriented communication solutions, which grant them a special character that distinguishes them from the others in the business.  </p>
                </div>
            </div>
        </div>
     </div>
     <div class="watdo-sec fw text-center">
     	<div class="container">
        	<div class="row">
            	<div class="col-md-12 do-title">
                	<img src="/assets/watimg.jpg" alt="">
                    <h5>What we do ?</h5>
                    <p>Every thing you need to do business intelligence right.</p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st1.jpg" alt="">
                    <h3>First step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st2.jpg" alt="">
                    <h3>Second step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st3.jpg" alt="">
                    <h3>Third step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st4.jpg" alt="">
                    <h3>Fourth step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st5.jpg" alt="">
                    <h3>Fifth step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-4">
                	<img src="/assets/st6.jpg" alt="">
                    <h3>Sixth step </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis </p>
                </div>
            </div>
        </div>
     </div>
     <div class="fw client_sec text-center">
     	<div class="container">
        	<div class="row">
            	<div class="col-md-8 col-md-offset-2">
                	<h4>OUR CLIENTS </h4>
                    <p>Donec sollicitudin molestie malesuada. Curabitur aliquet quam ici dui posuere blandit. NuIla porttitor accumsan tinci dunt. Quisque velit nisi, pretium ut lacinia in, elemena porttitor accumsan tincidun. </p>
                </div>
            </div>
            <ul>
            	<li><img src="/assets/jupiter.jpg" alt=""></li>
            	<li><img src="/assets/rocket.jpg" alt=""></li>
            	<li><img src="/assets/moonpic.jpg" alt=""></li>
            	<li><img src="/assets/mars.jpg" alt=""></li>
            	<li><img src="/assets/jupiter.jpg" alt=""></li>
            </ul>
        </div>
     </div>
     <div class="fw download_sec text-center">
     	<div class="container">
        	<div class="row">
            	<div class="col-md-8 col-md-offset-2">
                	<h4>DOWNLOAD IT </h4>
                    <p>Donec sollicitudin molestie malesuada. Curabitur aliquet quam ici dui posuere blandit. NuIla porttitor accumsan tinci dunt. Quisque velit nisi, pretium ut lacinia in, elemena porttitor accumsan tincidun. </p>
                    <a href="#">Apple store</a>
                    <a href="#">Play store</a>
                </div>
            </div>
        </div>
     </div>
</div>      

app/views/pages/contact.html.erb
<div class="container">
	<div class="row">
        <div class="col-md-12 text-center">
        	<ul class="breadcrumb">
            	<li><a href="#">Home</a></li>
            	<li>Contact</li>
            </ul>
           	<h1 class="page-title"><span>Contact Us</span></h1>
       </div>
       <div class="col-md-12">
       		<div class="contact-page">
            	<div class="row">
                	<div class="col-md-3 col-sm-3 text-center">
                    	<small class="text-center"><i class="fa fa-map-marker"></i></small>
                    	<h4>Address</h4>
                        <p>123 Avenue 1233 <br> New York, USA</p>
                    </div>
                    <div class="col-md-3 col-sm-3 text-center">
                    	<small class="text-center"><i class="fa fa-mobile"></i></small>
                    	<h4>Phone number</h4>
                        <p>+12 3456 789 101 <br> +12 3456 789 102</p>
                    </div>
                    <div class="col-md-3 col-sm-3 text-center">
                    	<small class="text-center"><i class="fa fa-envelope"></i></small>
                    	<h4>Email</h4>
                        <p><a href="mailto:hello@branddify.com">hello@branddify.com</a> <br> <a href="mailto:hi@hezy.org">hi@hezy.org</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 text-center">
                    	<small class="text-center"><i class="fa fa-question-circle"></i></small>
                    	<h4>Online support</h4>
                        <p>Skype ID 1: hezytheme <br> Skype ID 2: hezy</p>
                    </div>
                </div>
                <div class="row conatct-fields">
                	<div class="col-md-4 col-sm-4">
                    	<div class="form-group">
                            <div class="input-group">
                              <input type="text" class="form-control"  placeholder="your name">
                              <div class="input-group-addon"><i class="fa fa-user"></i></div>
                            </div>
                         </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                    	<div class="form-group">
                            <div class="input-group">
                              <input type="text" class="form-control"  placeholder="Email Address">
                              <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                            </div>
                         </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                    	<div class="form-group">
                            <div class="input-group">
                              <input type="text" class="form-control"  placeholder="Subject">
                              <div class="input-group-addon"><i class="fa fa-comment"></i></div>
                            </div>
                         </div>
                    </div>
                    <div class="col-md-12">
                    	<div class="form-group">
                        	<textarea class="form-control"></textarea>
                        </div>
                        <input type="submit" value="Submit" class="btn btn-success pull-right">
                    </div>
                </div>
            </div>
       </div>
    </div>
</div>      

app/views/pages/faqs.html.erb
<div class="container">
	<div class="row">
        <div class="col-md-12 text-center">
        	<ul class="breadcrumb">
            	<li><a href="#">Home</a></li>
            	<li>FAQ</li>
            </ul>
           	<h1 class="page-title"><span>FAQs</span></h1>
       </div>
       <div class="col-md-12">
       		<div class="panel-group faqpage" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title"><a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Who can sell online? </a></h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  <div class="panel-body">
                    <p>To really answer this question, I think the first question should be; “what can be sold online?” or “what can one sell online?” Either of these questions will help to answer the “who can sell online?” question.</p>

<p>You can sell either a service or a product online.</p>

<p>So if you provide any form of services to either consumers or companies, you are potentially qualified to sell online. And if you are a retailer or trader who buys and sells physical goods, you are also potentially qualified to sell online.
- See more at: </p>
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">What is the start-up cost for selling online?</a></h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="panel-body">
                    <p>The startup cost of selling online is quite small compared to selling offline. There are two approaches or models to 					                    selling online;</p>

                   <p>Creating your own e-Commerce site, or</p>

                   <p>Selling through other e-Commerce platforms, for example Kaymu</p>

                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                  <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">What are the necessary things needed to sell online?</a></h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                  <div class="panel-body">
                    <p>I think the answers provided above to question 2 and 3 should clearly suffice. However, let me summarize the necessary things needed to sell online;</p>
                   <p> <strong>Value proposition –</strong> this can be a product/service or a combination of both</p>
                    <p><strong>e-Commerce platform –</strong> this can be your own website or selling through other websites</p>
                    <p><strong>Internet access –</strong> you can acquire your own internet modem or use a cybercafé</p>
                   <p> <strong>e-Marketing skills –</strong> you can acquire them through training or simply hire an online marketing consultant to do the job</p>
                  </div>
                </div>
                </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingfour">
                  <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsefour" aria-expanded="false" aria-controls="collapsefour">What is the process of selling online? </a></h4>
                </div>
                <div id="collapsefour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingfour">
                  <div class="panel-body">
                    <p>The process of selling online, again depends on the model and nature of business you are involved in. There’s really no hard and fast rule or one-size-fits-all process to selling online. You have to evaluate the uniqueness of your own business and the peculiarities of your own situation through the guidance of an expert, coach or mentor. Only then, can the most suitable process be developed for you.</p>
                   <p> Do not be deceived, selling online is all about online marketing and there can be no form of marketing without a defined strategy. The process of selling online can only be defined from your online marketing strategy! </p>
                  </div>
                </div>
                </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingfive">
                  <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsefive" aria-expanded="false" aria-controls="collapsefive">What percentage of profit can I make on one sale online? </a></h4>
                </div>
                <div id="collapsefive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingfive">
                  <div class="panel-body">
                    <p>As you must have realized from my previous answers above, there are many factors to consider when it comes to selling online and because of these factors, most of which are peculiar to different businesses, the percentage of profit on one sale online is not fixed. It varies.</p>
<p>But having said that, here’s the very interesting part; the percentage of profit you can make from one sale online can be significantly higher than what you would make from the same sale offline. Why? Because online, the cost of providing the product/service is significantly lower than the cost of providing it offline.</p>
<p>So the percentage of profit you can make from one sale online, ultimately lies in your hand!</p>
                  </div>
                </div>
                </div>
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingsix">
                  <h4 class="panel-title"><a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsesix" aria-expanded="false" aria-controls="collapsesix">How do I build my reputation in selling online and how do I market my goods? </a></h4>
                </div>
                <div id="collapsesix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingsix">
                  <div class="panel-body">
                    <p>gain, this question is dependent on those factors I have already mentioned above. The way you would market a product is not the same way you would market a service. There are certain dynamics that must be considered while developing your online marketing strategy. </p>

<p>Regarding brand reputation building, the most critical factor that will determine how successful your online reputation will be is credibility. Without it, there is no way you will make any sale online. Before anyone will buy from you online, they need to know, like and trust you.</p>

<p>On the internet, sales are not made in an instant; sales are made by following-up on leads and getting them to know, like and trust your brand. This is why you need an effective follow-up system using content marketing.</p>
                  </div>
                </div>
                
              </div>
            </div>
       </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="navbar navbar-default navbar-static-bottom">
    <div class="container">
        <div class="navbar">
            <ul class="nav navbar-nav">
                <li><%= link_to "About", pages_about_path %></li>
                <li><%= link_to "Terms and Conditions", pages_about_path %></li>
                <li><%= link_to "Faqs", pages_faqs_path %></li>
                <li><%= link_to "Contact", pages_contact_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "BRANDDIFY", pages_about_path %> <br>
                <div class="copyright">Copyright &copy; BRANDDIFY 2015</div></a>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/stories/_form.html.erb
<div class="container-fluid story-tabs open">
  <div class="row">
    <div class="container">
      <div class="row">
      <div role="tabpanel" class="tab_panel form">
        <ul class="nav nav-tabs  nav-justified" role="tablist">
          <li role="presentation" class="active"><a href="#tab-0" aria-controls="tab-0" class="tab-0" role="tab" data-toggle="tab"><i class="fa fa-edit"></i> Dercription</a></li>
          <li role="presentation"><a href="#tab-1" aria-controls="tab-1" class="tab-1" role="tab" data-toggle="tab"><i class="fa fa-picture-o"></i> Uppload picture</a></li>
          <li role="presentation"><a href="#tab-2" aria-controls="tab-2" class="tab-2" role="tab" data-toggle="tab"><i class="fa fa-files-o"></i>Picture album</a></li>
        </ul>
        <div class="tab-content myowl">
          <div role="tabpanel" class="tab-pane active" id="tab-0">
            <div class="container">
              <div class="forma">
                <form role="form">
                  <%= form_for(@story, :html => { multipart: true }) do |f| %>
                    <% if @story.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>
                        <ul>
                        <% @story.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group">
                      <%= f.label :title %><br>
                      <%= f.text_field :title, class: 'form-control', placeholder: 'Add a title to your story' %>
                    </div>
                    <div class="form-group">
                      <%= f.label :description %><br>
                      <%= f.text_area :description, class: 'form-control', placeholder: 'Description of your story' %>
                    </div>
                    <div class="col-lg-5 col-lg-offset-5">
                      <div class="actions">
                        <%= f.submit 'Create Story', class: 'btn btn-success' %>
                      </div>
                    </div>
                  <% end %>
                </form>
              </div>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="tab-1">
            <div class="container">
              <input type="file">
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="tab-2">
            <div class="container">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<div class="container-fluid story">
    <a href="#">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="story-create">CREATE STORY<br><span class="plus">+</span><span class="minus">-</span></div>
            </div>
        </div>
    </a>
</div>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container main-content">
	<div class="row">
		<div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
			<div class="storydetail-container">
				<div class="single-story">
					<%= image_tag @story.image_url %>
					<p>
					  <strong>Title:</strong>
					  <%= @story.title %>
					</p>

					<p>
					  <strong>Description:</strong>
					  <%= @story.description %>
					</p>

					<%= link_to 'Edit', edit_story_path(@story) %> |
					<%= link_to 'Back', stories_path %>
				</div>
			</div>
		</div>
	</div>
</div>